### ISSUE TITLE
Further problems about beat detector

### ISSUE THREAD

**Issue by yongjiliu** [v4lk/lwbd#2]
It can be detected that when a beat occurs in a song through your program. Now, I have a new problem. Did you clap when someone is singing a song?  How to detect when i should clap? I‘m looking forward to your reply....

**Comment by qlyoung** [comment]
If I understand you correctly, you want to know if a given detected beat has a frequency signature that correlates with the sound made by clapping your hands. If that's the case, what you're wanting is instrument detection, which lwbd doesn't yet support. If that's not what you meant, please provide some more details.

**Comment by yongjiliu** [comment]
I‘m sorry for not expressing a clear meaning.Due to my lack of musical knowledge, I want to express my intent with a song.Did you heard a song called rolling in the deep(live) sung by Adele? In this song, you can heard that audience clap their hands according to the song's rhythm.Now,given an ordinary song(not a live song) , I want to know when  i should clap my hands. In other words,is it possible that computers know when to clap hands like audience in an ordinary song?
